WFCD/warframe-worldstate-parser

- src/parser.js
Date.now() is always greater than this.cache.creation
> Fix cache always being invalidated

- README.md
Documentation contained old wfcd name in url.
> Fix Documentation Link

- package.json
> fix: pin eslint-plugin-jsx-a11y to 6.0.3

- lib/ChallengeInstance.js
- lib/ConclaveChallenge.js
- lib/DailyDeal.js
- lib/DarkSector.js
- lib/Event.js
- lib/Fissure.js
- lib/FlashSale.js
- lib/GlobalUpgrade.js
- lib/Invasion.js
- lib/Mission.js
- lib/News.js
- lib/Nightwave.js
- lib/NightwaveChallenge.js
- lib/PersistentEnemy.js
- lib/Reward.js
- lib/Simaris.js
- lib/Sortie.js
- lib/SortieVariant.js
- lib/SyndicateJob.js
- lib/SyndicateMission.js
- lib/VoidTrader.js
- lib/WorldState.js
- lib/translation.js
- test/system_test.js
- test/translation_test.js
closes #36 
Use worldstate-data translations to provide translations.
Locale can be passed as a dependency to the parser.
Parser dependencies now fill in default objects where they're not overridden.
> Translations respect provided locale

- lib/CetusCycle.js
Making sure that CetusCycle#activation, when JSON.string'd becomes an iso date string.
> Ensure CetusCycle#activation ISO

- lib/CambionCycle.js
- lib/CetusCycle.js
- lib/ConclaveChallenge.js
- lib/Kuva.js
- lib/News.js
- lib/Sortie.js
- lib/SortieVariant.js
- package.json
- test/mocks/timeDate.js
- test/unit/cambion.spec.js
- test/unit/cetus.spec.js
- test/unit/construction.spec.js
- test/unit/invasion.spec.js
- test/unit/kuva.spec.js
- test/unit/mission.spec.js
- test/unit/news.spec.js
- test/unit/simaris.spec.js
- test/unit/sortie.spec.js
- test/unit/worldstate.spec.js
n/a
---
1. Run da tests
2. check da coverage
---
Added a bunch of coverage
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**
> improve coverage

- lib/Sortie.js
- lib/SyndicateMission.js
Added a `factionkey/SyndicateKey` to syndicates and Sorties for easier string matching
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **Yes**
- Have I run the linter? **No**
- Is is a bug fix, feature request, or enhancement? **Enhancement**
> feat: Add a faction key to Syndicates and Sorties

- lib/Mission.js
Fixed a typo in factions for Missions, should be `factionKey` instead of a second `faction`
---
You can see my fix [on this line](#71) for where the new data exists
> fix: a typo in `factionKey`

- lib/News.js
- test/data/LanguageNews.json
- test/unit/news.spec.js
Looks like DE is using a lang for it's discord join entry, this will in theory only translate the string when one is detected for both `message` and `translations`.
---
```json
{
"id": "62d31b87106360aa5703954d",
"message": "/Lotus/Language/CommunityMessages/JoinDiscord",
"link": "https://discord.com/invite/playwarframe",
"imageLink": "https://i.imgur.com/CNrsc7V.png",
"priority": false,
"date": "2022-07-16T20:10:00.000Z",
"eta": "66d 19h 13m 55s ago",
"update": false,
"primeAccess": false,
"stream": false,
"translations": {
"en": "/Lotus/Language/CommunityMessages/JoinDiscord",
"fr": "/Lotus/Language/CommunityMessages/JoinDiscord",
"it": "/Lotus/Language/CommunityMessages/JoinDiscord",
"de": "/Lotus/Language/CommunityMessages/JoinDiscord",
"es": …
```
> fix: translate news when there's a lang

- lib/News.js
Yeah so I messed up that part, when checking the translations string I forgot to add `message.Message`.
---
> fix: message not being passed correctly to translations

- lib/News.js
Mistake number 2 cancelling out the work that was done with `translator` with the second call to `this.translations[message.LanguageCode]`
---
```js
/**
* Translation of the news item
* @type {Object.<string, string>}
*/
this.translations = {};
data.Messages.forEach((message) => {
if (langString.test(message.Message)) {
this.translations[message.LanguageCode] = translator.languageString(message.Message, message.LanguageCode);
}
this.translations[message.LanguageCode] = message.Message;
});
```
- Does this introduce opinionated data formatting or manual data entry? **[No**
- Have I run the linter? **No**
- Is is a bug fix, feature …
> fix: translator being canceled out

- lib/WorldState.js
- test/integration/integration.spec.js
- test/unit/system.spec.js
closes #419 
---
When data doesn't come back from semlar, make sure data gets filled
---
default back to undefined if the keys of the arbitration are empty
- Does this introduce opinionated data formatting or manual data entry? **[Yes]**
> fix: make arbitration undefined when empty

- lib/NightwaveChallenge.js
- test/unit/nightwave.spec.js
When parsing nightwave weekly challenges `isDaily` would disappear from the data instead of defaulting to false.
---
1. parse worldstate.
---
> fix: Nightwave challenge `isDaily` default to false

- lib/CambionCycle.js
- lib/Fissure.js
- lib/WorldState.js
- lib/ZarimanCycle.js
- test/integration/integration.spec.js
This PR fixes [#440](https://github.com/WFCD/warframe-worldstate-parser/issues/440)
closes #440 
---
The error is already described in [#440](https://github.com/WFCD/warframe-worldstate-parser/issues/440)
A little summary : 
The type generated by the `build:types` command provided incorrect types for the property `fissures` in typescript projects, reporting this property as an array of News instead of Fissure
This PR fixes this minor issue
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
> fix(types): fissure, zariman, cambion syntax

- lib/DailyDeal.js
Added the ability to show the unique name of an item. Makes it easier to find the item in warframe-items.
---
- Is is a bug fix, feature request, or enhancement? **Enhancement**
> feat: Show the unique name for the item on sale

- lib/WorldState.js
closes #461
---
- When the void trader array was de-structured, specifically during tennocon baro visits, it would serve a different void trader each time. 
- Endpoint now returns an array sorted by inventory length in descending order, so tennocon baro always appears first (assuming he will always have a larger inventory than normal baro)
---
Fix is on lines 203 - 205
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**
> feat: Deprecated voidTrader endpoint for voidTraders

- lib/models/VoidTraderItem.js
Exposes and item's `uniqueName`. Should make it easier to find items in warframe-items, except of course new items.
---
---
- Is is a bug fix, feature request, or enhancement? **Enhancement**
> feat: expose `uniqueName` for `VoidTraderItem`s

- lib/models/NightwaveChallenge.js
- test/data/Nightwave.json
closes #486 
---
---
- Is is a bug fix, feature request, or enhancement? **[Feature]**
> feat: isPermanent

- lib/models/WorldEvent.js
---
/pc/events
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **N/A**
- Have I run the linter? **No**
> fix: factionless worldevent#tostring

- lib/models/SentientOutpost.js
- test/data/Tmp.js
- test/data/Tmp.json
- test/unit/sentientOutpost.spec.js
Modified the `sfn` regex to match the entire `sfn` key-value since `Temp` now has Deep Archimedea data in it
---
---
> fix: modified sentient outpost regex to only target the `sfn` key-value

- lib/WorldState.js
add default arbi data for [copium](https://canary.discord.com/channels/256087517353213954/1204130441440002068/1249818272975683634)
---
---
> fix: default arbi data

- lib/WorldState.js
Oh DE I get it but a warning would've been better. Anyways turns out Deep Archimedea data can be undefined
---
---
> fix: deep archimedea can be undefined in worldstate
