lib/Mission.js
=> Add nightmare and archwingRequired fields to Mission.js

lib/Alert.js, lib/ConclaveChallenge.js, lib/DailyDeal.js, lib/DarkSector.js, lib/DarkSectorBattle.js, lib/Event.js, lib/Fissure.js, lib/FlashSale.js, lib/GlobalUpgrade.js, lib/Invasion.js, lib/News.js, lib/Sortie.js, lib/SyndicateMission.js, lib/VoidTrader.js
Who thought that was a good idea? :P
=> Convert numberLong to number

README.md
So users can see how the data is structured
=> Add links to warframestat.us in README.md

.eslintrc.json, lib/ConstructionProgress.js, lib/WorldState.js, package.json, test/construction_test.js
adding ConstructionProgress for detailing build progress of fomorian and razorback armadas
=> Construction Progress

lib/GlobalUpgrade.js
Add missing function `getExpired`
Fixes #69
=> Fix issue #69

package.json
=> fix: pin eslint-plugin-react to 7.8.2

package.json
=> fix: pin semantic-release to 15.5.0

package-lock.json, package.json
=> Update semantic-release to the latest version 🚀

package.json
=> fix: pin eslint-plugin-import to 2.12.0

package.json
=> fix: pin eslint-config-airbnb to 17.0.0

package-lock.json, package.json
=> chore(dependencies): Greenkeeper/warframe worldstate data 0.0.430

package-lock.json, package.json
=> Greenkeeper/warframe worldstate data 0.0.440

lib/Alert.js, lib/CetusCycle.js, lib/ChallengeInstance.js, lib/ConclaveChallenge.js, lib/ConstructionProgress.js, lib/DarkSector.js, lib/EarthCycle.js, lib/Event.js, lib/Fissure.js, lib/Invasion.js, lib/News.js, lib/PersistentEnemy.js, lib/Sortie.js, lib/SyndicateJob.js, lib/SyndicateMission.js, lib/VoidTrader.js, lib/WeeklyChallenge.js, lib/WorldState.js, lib/WorldstateObject.js, lib/translation.js, package.json
add objects for weekly challenges
=> Weekly Challenge Parsing

.gitignore, .travis.yml, lib/DarkSector.js, lib/PersistentEnemy.js, lib/WorldEvent.js, package-lock.json, package.json
closes https://github.com/WFCD/warframe-status/issues/88
=> Health numbers

.codeclimate.yml, lib/CambionCycle.js, lib/Invasion.js, lib/SyndicateJob.js, lib/WorldState.js
cambion bounties support
closes #222 
closes #212
=> Cambion bounties

lib/SyndicateJob.js, package.json, test/data/isoVaultBounty.json, test/syndicatejob_test.js
=> fix: iso vault compat

test/integration/integration.spec.js
fixes for integration testing timeouts
---
N/A
---
see [here](https://github.com/WFCD/warframe-worldstate-parser/pull/278/files#diff-5a6ac18ee73aa8f7f7664949f01c57fa72bd703ea0349c51e0c12bedc468b52cR25)
=> chore(ci): improve ci flow for integration tests

lib/News.js
---
parse current ws
---
You can see my fix [on this line](#line-number-1235234) for where the new data exists
- Does this contain a new dependency? **[Yes/No]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes/No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes/No]**
- Have I run the linter? **[Yes/No]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix/Feature/Enhancement]**
=> fix: unparseable news

lib/Kuva.js, lib/Mission.js
N/A - purely for inheritance/similar formatting
---
---
=> fix(i18n): add more standardized keys

.gitignore, package.json
=> ci: fix prepublish script

package-lock.json, package.json
fix not using postinstall
---
---
=> chore(package): postinstall script

lib/WorldState.js, lib/ZarimanCycle.js, test/integration/integration.spec.js, test/unit/zariman.spec.js
ZarimanCycle logic has been corrected
https://github.com/WFCD/warframe-worldstate-parser/commit/2291662687819f50d7bcd8fdee6fceadd3a9c992#diff-2c64bac2942d6634d0f40eecd6a8437148253bff7f661f8b7644cfcbfab71721R102
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
=> fix: zarimanCycle logic

lib/WorldState.js, lib/models/DuviriCycle.js, lib/supporting/DuviriChoice.js, package.json, test/integration/integration.spec.js
closes #455
---
add field data for XpChoices
---
- Does this introduce opinionated data formatting or manual data entry? **[Yes - opinionated]**
- Is is a bug fix, feature request, or enhancement? **[Feature]**
=> feat: add duviri choices

lib/models/DuviriCycle.js
closes #480 
---
smooth out seconds & milliseconds like other cycles
---
=> fix: smooth duviri times

lib/models/Kuva.js
lint fix
---
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
=> fix: lint fix

package-lock.json, package.json
=> fix(packge): remove unneeded deps & update engines

.c8rc.json, .commitlintrc.ts, .eslintignore, .eslintrc.yaml, .lintstagedrc.yaml, .mocharc.yml, .npmignore, README.md, babel.config.cjs, clean-package.config.js, lib/WorldState.js, lib/models/SyndicateJob.js, lib/models/SyndicateMission.js, lib/models/WorldEvent.js, main.js, package-lock.json, package.json, test/integration/integration.spec.js, test/unit/event.spec.js, test/unit/syndicatejob.spec.js, test/unit/syndicatemission.spec.js, test/unit/system.spec.js, test/unit/worldstate.spec.js
BREAKING CHANGE: async data moved to build functions
---
---
- Does this introduce opinionated data formatting or manual data entry? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**
=> feat: change how syndcate arrays parse

.eslintrc.yaml, .lintstagedrc.yaml, .npmignore, clean-package.config.cjs, lib/WorldState.js, lib/supporting/RewardTypes.js, package-lock.json, package.json, test/testclient.js, tsconfig.declaration.json
fix redos issue
fix weird release issue
---
---
- Does this contain a new dependency? **[Yes]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
=> fix(sec): redos, release

lib/WorldState.js, lib/models/DeepArchidemea.js, package-lock.json, package.json, test/data/DeepArchimedea.json, test/unit/deeparchimedea.spec.js
Added Deep Archimedea, it's not a stable since DE doesn't always refresh the data to match the week but in case they do fix it here it is
```json
{
"id": "1728259200000DeepArchimedea",
"activation": "2024-10-07T00:00:00.000Z",
"expiry": "2024-10-14T00:00:00.000Z",
"missions": [
{
"mission": "Extermination",
"deviation": {
"key": "NecramechActivation",
"name": "Necramech Activation",
"description": "[PH] Necramech Activation Desc"
},
"riskVariables": [
{
"key": "ExplosiveCrawlers",
"name": "Explosive Crawlers",
"description": "[PH] Explosive Crawlers Desc"
},
{
"key": "Voidburst",
"name": "Postmortal Surges",
"description": "Slain enemies burts with Void enerhy."
}
]
},
{
"mission": "Survival",
"deviation": {
"key": "NecramechLockout",
"name": "Necramech Lockout",
"description": "[PH] …
```
=> feat: added Deep Archimedea
